name: plexys-homework

services:
  server:
    image: cortezaproject/corteza:${VERSION:-2024.9.10}
    restart: unless-stopped
    depends_on:
    - db
    ports:
      - "127.0.0.1:18080:80"
    environment:
      DOMAIN: "${DOMAIN:-localhost:18080}"
      DB_DSN: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/corteza?sslmode=disable"
      HTTP_WEBAPP_ENABLED: "true"
      AUTH_JWT_SECRET: "${AUTH_JWT_SECRET}"
      CORREDOR_ENABLED: "false"
    volumes:
      - server-data:/data

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: corteza
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  server-data:
  db-data:
